
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Allow `prisma generate` during CI install steps where DATABASE_URL may not be set yet.
    url: process.env.DATABASE_URL ?? "postgresql://neondb_owner:npg_eJh4GoMn2UlF@ep-morning-brook-adks2qk9-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
  },
});
